# Site settings
title: Zen的博客
email: 15026928710@163.com
description: > #我想拥有一种神奇的墨水，点到那里那里就会有奇迹。
baseurl: "http://ifday.net" # the subpath of your site, e.g. /blog/
url: "http://ifday.net" # the base hostname & protocol for your site
twitter_username:  Zen
github_username:  NPF123

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 牛鹏飞
  email: 15026928710@163.com
  link: http://ifday.net
  weibo: 
  github: http://github.com/NPF123
title: Zen的博客                             #自定义常量

# avatar头像及Favicon
avatar: https://avatars1.githubusercontent.com/u/5010799?v=3&amp;s=460
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: 

# disqus 设置
disqus:
  shortname: Zen
